# SFO configuration (YAML) — Rules Engine v1
version: 1

default_action: move            # move | copy
collision: rename               # skip | rename | overwrite
trash_dir: "~/.local/share/sfo/trash"

ignore:
  - "**/.git/**"
  - "**/node_modules/**"
  - "**/.DS_Store"

# Rules are evaluated in order; FIRST match wins.
# Supported types (v1): extension | regex | mtime
# target_template tokens available: {name} {ext} {yyyy} {mm} {dd}
rules:
  - name: images_by_extension
    type: extension
    pattern: "jpg,jpeg,png"
    target_template: "images/{ext}/{yyyy}/{mm}/"

  - name: logs_by_regex
    type: regex
    pattern: ".*\\.log$"
    target_template: "logs/{yyyy}/{mm}/{dd}/"

  - name: everything_else_by_mtime
    type: mtime
    # optional: you could add a 'when' like "*.txt" to limit scope
    target_template: "{yyyy}/{mm}/"
