# SFO configuration (YAML) — Rules Engine v1
version: 1

default_action: move            # move | copy
collision: rename               # skip | rename | overwrite
trash_dir: "~/.local/share/sfo/trash"

ignore:
  - "**/.git/**"
  - "**/node_modules/**"
  - "**/.DS_Store"

# Rules are evaluated in order; FIRST match wins.
# Supported types (v1): extension | regex | mtime | hash
# target_template tokens available: {name} {ext} {yyyy} {mm} {dd} {hash} {hash_prefix}
rules:
  - name: dedupe_by_hash
    type: hash
    # all files not otherwise ignored will be hashed.
    # first-seen files are moved according to target_template.
    # subsequent identical files are moved to duplicates/{hash_prefix}.
    target_template: "unique_files/"
    hash_prefix_len: 2  # optional, default 2

  - name: images_by_extension
    type: extension
    pattern: "jpg,jpeg,png"
    target_template: "images/{ext}/{yyyy}/{mm}/"

  - name: logs_by_regex
    type: regex
    pattern: ".*\\.log$"
    target_template: "logs/{yyyy}/{mm}/{dd}/"

  - name: everything_else_by_mtime
    type: mtime
    # optional: you could add a 'when' like "*.txt" to limit scope
    target_template: "{yyyy}/{mm}/"
